### ISSUE TITLE
Please add random seed 

### ISSUE THREAD

**Issue by razvanab** [ScreamingHawk/comfyui-ollama-prompt-encode#6]
Please add random seed. This helps us by not having to change the prompt slightly all the time.

**Comment by ScreamingHawk** [comment]
See #3 . 

Seed is not returning consistent results due to a bug in llama. 
I'll merge the seed branch to force different results but we won't see consistent results when reusing the seed.

**Comment by ScreamingHawk** [comment]
Added! v2.0.0 will be out shortly with changes

**Comment by razvanab** [comment]
Great Thanks.
